# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required version key
version: 2

# Set the Python version and any additional tools required
build:
  os: ubuntu-22.04  # Default OS
  tools:
    python: "3.9"  # Specify Python version

# Define where the Sphinx configuration file is located
sphinx:
  configuration: docs/conf.py  # Path to the Sphinx conf.py

# Specify the Python dependencies needed to build the documentation
python:
  install:
    - requirements: docs/requirements.txt  # Path to the requirements file for building docs
    