name: Mypy

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  mypy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install types-requests==2.32.0.20240914
          pip install types-pygments==2.18.0.20240506

      - name: Run mypy
        run: |
          mypy deluge_web_client
