name: CI Pipeline

on:
  push:
    branches:
      - typing # Run mypy check on pushes to the typing branch
  pull_request:
    branches:
      - typing # Run mypy check on PRs to the typing branch
  release:
    types:
      - created # Run the publish job only when a release is created

jobs:
  mypy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install types-requests==2.32.0.20240914
          pip install types-pygments==2.18.0.20240506

      - name: Run mypy
        run: |
          mypy deluge_web_client

  publish_to_pypi:
    if: github.event_name == 'release' # Only run this job if a release is created
    name: Publish Python to PyPI
    needs: mypy_check # Only run this job if mypy_check passes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: |
          python -m build  # Build the distribution files (wheel and source dist)

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
