name: Publish to TestPyPI

on:
  push:
    branches:
      - typing # Only run this workflow on pushes to the main branch
  pull_request:
    branches:
      - typing # Optional: also run on PRs to main for mypy check

jobs:
  mypy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install types-requests==2.32.0.20240914
          pip install types-pygments==2.18.0.20240506

      - name: Run mypy
        run: |
          mypy deluge_web_client

  publish_to_testpypi:
    name: Publish Python to TestPyPI
    needs: mypy_check # Only run this job if mypy_check passes
    runs-on: ubuntu-latest

    environment: 
      name: testpypi
      url: https://test.pypi.org/p/deluge-web-client

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: |
          python -m build  # Build the distribution files (wheel and source dist)

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1     
        with:
          repository-url: https://test.pypi.org/legacy/         
