name: Ruff

on:
#   push:
#     branches:
#       - "**"
  pull_request:
    branches:
      - "**"

jobs:
  ruff_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: |
          ruff check deluge_web_client --exit-zero
