name: Test DelugeWebClient

on:
  pull_request:
    branches:
      - "**"
  # workflow_dispatch:

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
